name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - staging

permissions:
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test -Denv=${{ github.event.inputs.env || 'dev' }}

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
      - name: Run Allure Action
        uses: allure-framework/allure-report@v0
        with:
          # Path to the generated report directory
          # By default, it's set to `./allure-report`
          report-directory: "./allure-report"
          # GitHub Token that's used for posting the comments in Pull Requests
          github-token: ${{ secrets.GITHUB_TOKEN }}